apiVersion: v1
kind: ConfigMap
metadata:
  name: vo-dang-${DEPLOY_ENV}-config
  namespace: vo-dang-${DEPLOY_ENV}-env
  labels:
    app: vo-dang-platform
    env: ${DEPLOY_ENV}
data:
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PORT: "${DB_PORT}"
  DB_URL: "${DB_URL}"
  JWT_ALGORITHM: "${JWT_ALGORITHM}"
  JWT_EXPIRE: "${JWT_EXPIRE}"
  ALLOWED_DOMAINS: "${ALLOWED_DOMAINS}"
  GLOBAL_DOMAIN: "${GLOBAL_DOMAIN}"
  REDIS_ADDRESS: "${REDIS_ADDRESS}"
  REDIS_DB: "${REDIS_DB}"