apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: green-mind-backend-hpa
  namespace: vo-dang-${DEPLOY_ENV}-env
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: green-mind-backend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
