apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: vo-dang-${DEPLOY_ENV}-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
#  storageClassName: local-path
