apiVersion: v1
kind: Secret
metadata:
  name: vo-dang-${DEPLOY_ENV}-secret
  namespace: vo-dang-${DEPLOY_ENV}-env
type: Opaque
stringData:
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"