apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-email-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  DB_HOST: "${DB_HOST}"
